name: deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2

    - name: dependencies
      run: |
        sudo apt-get update -qy
        sudo apt-get install -y make jq curl
      shell: bash

    - name: build
      run: |
        make
      working-directory: .

    - name: deploy
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git checkout --orphan gh-pages
        git rm -rf .
        mv out/* .
        git add .
        git commit -m 'deploy to pages'
        git branch -M gh-pages
        git push -f "https://github.com/${{ github.repository }}" gh-pages
      working-directory: .
      env:
        GH_PAGES_TOKEN: ${{ secrets.GH_PAGES_TOKEN }}

    - name: clean
      run: |
        make clean
        git checkout main
      working-directory: .
